services:
  victimedebian:
    build: ./ldpreload_malware
    ports:
      - "5000:5000"
    command: ["tail", "-f", "/dev/null"]
    networks:
      mynetwork: 
        ipv4_address: 172.21.0.10
  victimessh:
    build: .
    ports:
      - "5001:22"
    # command: ["tail", "-f", "/dev/null"]
    networks:
      mynetwork: 
        ipv4_address: 172.21.0.11

  serverc2:
    build: ./server
    ports:
      - "6000:6000"
    volumes:
      - ./db:/server/db
    command: ["tail", "-f", "/dev/null"]
    # command: /server/server
    networks:
      mynetwork: 
        ipv4_address: 172.21.0.12

        
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
